name: Update Repository Field

on:
  create:
    types: [repository]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update package.json
        run: |
          node ./scripts/update-repo.js ${{ github.event.repository.html_url }}
